version : '2'
services:
  web: 
    build: .
    image: application
    restart: always
    depends_on:
      - db
    ports:
      - '80:8080'        
    networks:
      - networkApplication

  db:
    container_name: bdd
    image: mysql
    environment:
      - MYSQL_USER=yamine
      - MYSQL_PASSWORD=yamine
      - MYSQL_DATABASE=gestionarticle
      - MYSQL_ALLOW_EMPTY_PASSWORD=non
    networks:
      - networkApplication

networks:
  networkApplication:
    driver: bridge

  
      

        
        
        